apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-healthcheck-config
data:
  healthcheck.conf: |
    server {
      listen 80;

      location /healthz {
        access_log off;
        return 200 'OK';
        add_header Content-Type text/plain;
      }
    }